---
- name: play level variables using vars_files
  hosts: local
  connection: local
  vars:
    Name: Mahesh
  vars_files:
   - course.yml
  vars_prompt:
    - name: Name 
      prompt: Provide the Name?
  tasks:
   - name: Print name
     vars:
        Name: ARK
     ansible.builtin.debug:
        msg: "my Name is {{ Name }}"


# 1. extra vars from command 
# 2. vars_files
# 3. vars_prompt
# 4. Task Variables
# 5. Play Variables
