---
- name: loops
  hosts: local
  connection: local
  become: true
  tasks:
   - name: loops with names
     ansible.builtin.package:
       name: "{{ item }}"
       state: present
     loop:
       - nginx
       - mysql
       - nodejs