---
- name: loops
  hosts: local
  connection: local
  become: true
  tasks:
   - name: loops with names
     ansible.builtin.package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
     loop: # list of map
       - { name: "mysql", state: absent } #map/dict
       - { name: "nginx", state: absent }
       - { name: "htop", state: present }

